<?php

namespace Database\Seeders;

use App\Models\ChartOfAccount;
use App\Models\Erkap\CostElement;
use Illuminate\Database\Seeder;

class CostElementsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $chartOfAccounts = ChartOfAccount::pluck('id', 'code')->all();
        $costElements = [
            ["code" => "6000", "name" => "Pendapatan Penjualan Batubara BUKIT ASAM 45", "erkap_cost_element_category_id" => 1],
            ["code" => "6001", "name" => "Pendapatan Penjualan Batubara BUKIT ASAM 50", "erkap_cost_element_category_id" => 1],
            ["code" => "6002", "name" => "Pendapatan Penjualan Batubara BUKIT ASAM 55", "erkap_cost_element_category_id" => 1],
            ["code" => "6003", "name" => "Pendapatan Penjualan Batubara BUKIT ASAM 64 HS", "erkap_cost_element_category_id" => 1],
            ["code" => "6004", "name" => "Pendapatan Penjualan Batubara BUKIT ASAM 64 LS / GAR 6400", "erkap_cost_element_category_id" => 1],
            ["code" => "6005", "name" => "Pendapatan Penjualan Batubara GAR 5800", "erkap_cost_element_category_id" => 1],
            ["code" => "6006", "name" => "Pendapatan Penjualan Batubara GAR 5900", "erkap_cost_element_category_id" => 1],
            ["code" => "6007", "name" => "Pendapatan Penjualan Batubara GAR 6100", "erkap_cost_element_category_id" => 1],
            ["code" => "6008", "name" => "Pendapatan Penjualan Batubara GAD 7300", "erkap_cost_element_category_id" => 1],
            ["code" => "6009", "name" => "Pendapatan Penjualan Batubara SEMI ANS", "erkap_cost_element_category_id" => 1],
            ["code" => "6010", "name" => "Pendapatan Penjualan Batubara GAR 4700", "erkap_cost_element_category_id" => 1],
            ["code" => "6011", "name" => "Pendapatan Penjualan Batubara BAS 4800", "erkap_cost_element_category_id" => 1],
            ["code" => "6012", "name" => "Pendapatan Penjualan Batubara GAR 6700", "erkap_cost_element_category_id" => 1],
            ["code" => "6025", "name" => "Pendapatan DMO", "erkap_cost_element_category_id" => 1],
            ["code" => "6030", "name" => "Pendapatan Penjualan Batu Pecah", "erkap_cost_element_category_id" => 1],
            ["code" => "6040", "name" => "Pendapatan Listrik - Komponen A", "erkap_cost_element_category_id" => 2],
            ["code" => "6041", "name" => "Pendapatan Listrik - Komponen B", "erkap_cost_element_category_id" => 2],
            ["code" => "6042", "name" => "Pendapatan Listrik - Komponen C", "erkap_cost_element_category_id" => 2],
            ["code" => "6043", "name" => "Pendapatan Listrik - Komponen D", "erkap_cost_element_category_id" => 2],
            ["code" => "6044", "name" => "Pendapatan Listrik - Komponen E", "erkap_cost_element_category_id" => 2],
            ["code" => "6045", "name" => "Pendapatan Penjualan Kelebihan Tenaga Listrik (Excess Power)", "erkap_cost_element_category_id" => 2],
            ["code" => "6050", "name" => "Pendapatan Penjualan Briket Super", "erkap_cost_element_category_id" => 3],
            ["code" => "6051", "name" => "Pendapatan Penjualan Briket Telur", "erkap_cost_element_category_id" => 3],
            ["code" => "6052", "name" => "Pendapatan Penjualan Briket Kubus", "erkap_cost_element_category_id" => 3],
            ["code" => "6053", "name" => "Pendapatan Penjualan Briket Arang Batok Kelapa", "erkap_cost_element_category_id" => 3],
            ["code" => "6054", "name" => "Pendapatan Penjualan Karbon Aktif", "erkap_cost_element_category_id" => 3],
            ["code" => "6060", "name" => "Pendapatan Jasa Angkutan Kapal", "erkap_cost_element_category_id" => 4],
            ["code" => "6061", "name" => "Pendapatan Sewa Dermaga", "erkap_cost_element_category_id" => 4],
            ["code" => "6062", "name" => "Pendapatan Pengiriman", "erkap_cost_element_category_id" => 4],
            ["code" => "6067", "name" => "Pendapatan Jasa Bongkar Muat", "erkap_cost_element_category_id" => 4],
            ["code" => "6070", "name" => "Pendapatan Jasa Teknik", "erkap_cost_element_category_id" => 5],
            ["code" => "6071", "name" => "Pendapatan Jasa Laboratorium", "erkap_cost_element_category_id" => 5],
            ["code" => "6080", "name" => "Pendapatan Jasa Penambangan", "erkap_cost_element_category_id" => 6],
            ["code" => "6081", "name" => "Pendapatan Jasa Pengupasan Tanah (Overburden)", "erkap_cost_element_category_id" => 6],
            ["code" => "6082", "name" => "Pendapatan Sewa Peralatan Tambang", "erkap_cost_element_category_id" => 6],
            ["code" => "6100", "name" => "Pendapatan Penjualan CPO", "erkap_cost_element_category_id" => 7],
            ["code" => "6101", "name" => "Pendapatan Penjualan PK", "erkap_cost_element_category_id" => 7],
            ["code" => "6102", "name" => "Pendapatan Penjualan Cangkang", "erkap_cost_element_category_id" => 7],
            ["code" => "6103", "name" => "Pendapatan Penjualan Janjangan", "erkap_cost_element_category_id" => 7],
            ["code" => "6104", "name" => "Pendapatan Penjualan Fiber", "erkap_cost_element_category_id" => 7],
            ["code" => "6105", "name" => "Pendapatan Penjualan Tankos", "erkap_cost_element_category_id" => 7],
            ["code" => "6106", "name" => "Pendapatan Penjualan TBS", "erkap_cost_element_category_id" => 7],
            ["code" => "6107", "name" => "Pendapatan Penjualan Composting", "erkap_cost_element_category_id" => 7],
            ["code" => "6108", "name" => "Pendapatan Penjualan Karet", "erkap_cost_element_category_id" => 7],
            ["code" => "6109", "name" => "Pendapatan Penjualan Singkong", "erkap_cost_element_category_id" => 7],
            ["code" => "6110", "name" => "Pendapatan Penjualan Keagenan", "erkap_cost_element_category_id" => 7],
            ["code" => "6111", "name" => "Pendapatan Penjualan Rawat Jalan", "erkap_cost_element_category_id" => 7],
            ["code" => "6112", "name" => "Pendapatan Penjualan Rawat Inap", "erkap_cost_element_category_id" => 7],
            ["code" => "6113", "name" => "Pendapatan Penjualan MCU", "erkap_cost_element_category_id" => 7],
            ["code" => "6114", "name" => "Pendapatan Penjualan BPJS", "erkap_cost_element_category_id" => 7],
            ["code" => "6115", "name" => "Pendapatan Penjualan Farmasi", "erkap_cost_element_category_id" => 7],
            ["code" => "6116", "name" => "Pendapatan Penjualan Klinik", "erkap_cost_element_category_id" => 7],
            ["code" => "6200", "name" => "Pendapatan CBM", "erkap_cost_element_category_id" => 8],
            ["code" => "6225", "name" => "Pendapatan Benefisiasi Batu Bara", "erkap_cost_element_category_id" => 8],
            ["code" => "6300", "name" => "Pendapatan Jasa O&M", "erkap_cost_element_category_id" => 9],
            ["code" => "6900", "name" => "Pendapatan Bunga Bank/Jasa Giro", "erkap_cost_element_category_id" => 10],
            ["code" => "6901", "name" => "Pendapatan Bunga Investasi Derivatif", "erkap_cost_element_category_id" => 10],
            ["code" => "6902", "name" => "Pendapatan Bunga Obligasi", "erkap_cost_element_category_id" => 10],
            ["code" => "6903", "name" => "Pendapatan Bunga Deposito", "erkap_cost_element_category_id" => 10],
            ["code" => "6904", "name" => "Pendapatan Sewa Infrastruktur dan Fasilitas Perusahaan", "erkap_cost_element_category_id" => 10],
            ["code" => "6905", "name" => "Pendapatan Bunga Deposito DHE", "erkap_cost_element_category_id" => 10],
            ["code" => "6920", "name" => "Pendapatan Penjualan Dokumen Tender", "erkap_cost_element_category_id" => 11],
            ["code" => "6921", "name" => "Pendapatan Denda/Klaim", "erkap_cost_element_category_id" => 11],
            ["code" => "6925", "name" => "Pendapatan Dividen", "erkap_cost_element_category_id" => 11],
            ["code" => "6922", "name" => "Pendapatan Selisih Harga  Penj. Saham", "erkap_cost_element_category_id" => 11],
            ["code" => "6923", "name" => "Penerimaan Potongan Harga", "erkap_cost_element_category_id" => 11],
            ["code" => "6924", "name" => "Pendapatan Kelebihan Pajak", "erkap_cost_element_category_id" => 11],
            ["code" => "6930", "name" => "Pendapatan Penjualan Aktiva Tetap", "erkap_cost_element_category_id" => 12],
            ["code" => "6940", "name" => "Pendapatan Penjualan Material Rongsokan", "erkap_cost_element_category_id" => 13],
            ["code" => "6941", "name" => "Pendapatan Bunga PKK", "erkap_cost_element_category_id" => 13],
            ["code" => "6942", "name" => "Pendapatan Tunda Pandu Dan Moring", "erkap_cost_element_category_id" => 13],
            ["code" => "7000", "name" => "Biaya Konsultan", "erkap_cost_element_category_id" => 14],
            ["code" => "7001", "name" => "Biaya Jasa Pengupasan Lapisan Tanah (Overburden)", "erkap_cost_element_category_id" => 14],
            ["code" => "7002", "name" => "Biaya Jasa Kontraktor (ADP)", "erkap_cost_element_category_id" => 14],
            ["code" => "8000", "name" => "Biaya Gaji", "erkap_cost_element_category_id" => 15],
            ["code" => "8001", "name" => "Biaya Upah Karyawan Harian Lepas", "erkap_cost_element_category_id" => 15],
            ["code" => "8002", "name" => "Biaya Honorarium/KKWT", "erkap_cost_element_category_id" => 15],
            ["code" => "8003", "name" => "Tunjangan Lembur", "erkap_cost_element_category_id" => 15],
            ["code" => "8004", "name" => "Biaya Kewajiban Pensiun (PSL)", "erkap_cost_element_category_id" => 15],
            ["code" => "8005", "name" => "Tunjangan PPh 21", "erkap_cost_element_category_id" => 15],
            ["code" => "8006", "name" => "Tunjangan Pegawai", "erkap_cost_element_category_id" => 15],
            ["code" => "8007", "name" => "Tunjangan Giliran/Shift", "erkap_cost_element_category_id" => 15],
            ["code" => "8008", "name" => "Tunjangan Makan", "erkap_cost_element_category_id" => 15],
            ["code" => "8009", "name" => "Tunjangan Perumahan", "erkap_cost_element_category_id" => 15],
            ["code" => "8010", "name" => "Tunjangan Cuti", "erkap_cost_element_category_id" => 15],
            ["code" => "8011", "name" => "Insentif dan Jasa Produksi", "erkap_cost_element_category_id" => 15],
            ["code" => "8012", "name" => "Tunjangan Transportasi", "erkap_cost_element_category_id" => 15],
            ["code" => "8013", "name" => "Tunjangan Prestasi", "erkap_cost_element_category_id" => 15],
            ["code" => "8014", "name" => "Tunjangan Pengobatan", "erkap_cost_element_category_id" => 15],
            ["code" => "8015", "name" => "Tunjangan Hari Raya", "erkap_cost_element_category_id" => 15],
            ["code" => "8016", "name" => "Biaya Pesangon & Uang Jasa", "erkap_cost_element_category_id" => 15],
            ["code" => "8017", "name" => "Tunjangan Sosial Kematian", "erkap_cost_element_category_id" => 15],
            ["code" => "8100", "name" => "Biaya Bahan Bakar Minyak", "erkap_cost_element_category_id" => 16],
            ["code" => "8101", "name" => "Biaya Minyak dan Pelumas", "erkap_cost_element_category_id" => 17],
            ["code" => "8102", "name" => "Biaya Bahan Peledak", "erkap_cost_element_category_id" => 18],
            ["code" => "8103", "name" => "Biaya Bahan Kimia", "erkap_cost_element_category_id" => 18],
            ["code" => "8104", "name" => "Biaya Material dan Suku Cadang", "erkap_cost_element_category_id" => 18],
            ["code" => "8105", "name" => "Biaya Ban", "erkap_cost_element_category_id" => 18],
            ["code" => "8106", "name" => "Biaya Pemboran & Aksesoris", "erkap_cost_element_category_id" => 18],
            ["code" => "8107", "name" => "Biaya Ground Engaging Tools (GET)", "erkap_cost_element_category_id" => 18],
            ["code" => "8108", "name" => "Biaya Undercarriage", "erkap_cost_element_category_id" => 18],
            ["code" => "8109", "name" => "Biaya Common Tools", "erkap_cost_element_category_id" => 18],
            ["code" => "8110", "name" => "Biaya Varians Persediaan Pembelian Barang", "erkap_cost_element_category_id" => 18],
            ["code" => "8118", "name" => "Biaya Pembelian Aset Tidak Dikapitalisir", "erkap_cost_element_category_id" => 18],
            ["code" => "7013", "name" => "Biaya Sewa Alat Berat", "erkap_cost_element_category_id" => 19],
            ["code" => "7014", "name" => "Biaya Sewa Peralatan dan Perlengkapan Operasional", "erkap_cost_element_category_id" => 20],
            ["code" => "7015", "name" => "Biaya Sewa Peralatan dan Perlengkapan Non-Operasional", "erkap_cost_element_category_id" => 20],
            ["code" => "7016", "name" => "Biaya Sewa Kendaraan Bermotor Operasional", "erkap_cost_element_category_id" => 20],
            ["code" => "7017", "name" => "Biaya Sewa Kendaraan Bermotor Non Operasional", "erkap_cost_element_category_id" => 20],
            ["code" => "7018", "name" => "Biaya Sewa Gudang/Kantor", "erkap_cost_element_category_id" => 20],
            ["code" => "7019", "name" => "Biaya Sewa Peralatan dan Perlengkapan Kantor", "erkap_cost_element_category_id" => 20],
            ["code" => "7020", "name" => "Biaya Sewa Infrastruktur dan Fasilitas Perusahaan", "erkap_cost_element_category_id" => 20],
            ["code" => "7021", "name" => "Biaya Sewa Rumah Dinas/Mess", "erkap_cost_element_category_id" => 20],
            ["code" => "7022", "name" => "Biaya Sewa Lahan/Tanah", "erkap_cost_element_category_id" => 20],
            ["code" => "7023", "name" => "Biaya Angkutan Truk/Mobilisasi", "erkap_cost_element_category_id" => 20],
            ["code" => "7012", "name" => "Biaya Jasa Galian Batubara", "erkap_cost_element_category_id" => 21],
            ["code" => "7003", "name" => "Biaya Jasa Surveyor", "erkap_cost_element_category_id" => 22],
            ["code" => "7004", "name" => "Biaya Jasa Pemasaran", "erkap_cost_element_category_id" => 22],
            ["code" => "7005", "name" => "Biaya Pembuatan Laporan Audit", "erkap_cost_element_category_id" => 22],
            ["code" => "7006", "name" => "Biaya Upah Non Karyawan", "erkap_cost_element_category_id" => 22],
            ["code" => "7007", "name" => "Biaya Pelayanan Kebersihan dan Keamanan", "erkap_cost_element_category_id" => 22],
            ["code" => "7008", "name" => "Biaya Penjamin Emisi Saham", "erkap_cost_element_category_id" => 22],
            ["code" => "7009", "name" => "Biaya Jasa Kontraktor Perawatan", "erkap_cost_element_category_id" => 22],
            ["code" => "7010", "name" => "Biaya Jasa Non Kontraktor Perawatan", "erkap_cost_element_category_id" => 22],
            ["code" => "7011", "name" => "Biaya Jasa Klinik Kesehatan", "erkap_cost_element_category_id" => 22],
            ["code" => "8205", "name" => "Biaya Lisensi dan Perizinan", "erkap_cost_element_category_id" => 23],
            ["code" => "8019", "name" => "Biaya Perjalanan Dinas", "erkap_cost_element_category_id" => 24],
            ["code" => "8400", "name" => "Biaya Penyusutan Alat Tambang/Pelabuhan Utama", "erkap_cost_element_category_id" => 25],
            ["code" => "8401", "name" => "Biaya Penyusutan Bangunan dan infrastuktur", "erkap_cost_element_category_id" => 25],
            ["code" => "8402", "name" => "Biaya Penyusutan Mesin dan Peralatan", "erkap_cost_element_category_id" => 25],
            ["code" => "8403", "name" => "Biaya Penyusutan Kendaraan Bermotor", "erkap_cost_element_category_id" => 25],
            ["code" => "8404", "name" => "Biaya Penyusutan Perlengkapan Kantor", "erkap_cost_element_category_id" => 25],
            ["code" => "8405", "name" => "Biaya Penyusutan Peralatan Engineering", "erkap_cost_element_category_id" => 25],
            ["code" => "8406", "name" => "Biaya Penyusutan Komponen Alat Berat", "erkap_cost_element_category_id" => 25],
            ["code" => "8407", "name" => "Biaya Penyusutan Peralatan Pembantu Tambang", "erkap_cost_element_category_id" => 25],
            ["code" => "8408", "name" => "Biaya Penyusutan Alat Tambang/Pelabuhan Utama - SGU", "erkap_cost_element_category_id" => 25],
            ["code" => "8409", "name" => "Biaya Penyusutan Peralatan Pembantu Tambang - SGU", "erkap_cost_element_category_id" => 25],
            ["code" => "8410", "name" => "Biaya penyusutan Hak Guna Aset - PSAK 73", "erkap_cost_element_category_id" => 25],
            ["code" => "8411", "name" => "Biaya Amortisasi aset tidak berwujud", "erkap_cost_element_category_id" => 25],
            ["code" => "8018", "name" => "Biaya Pendidikan dan Pelatihan", "erkap_cost_element_category_id" => 26],
            ["code" => "8300", "name" => "Biaya CSR dan Comdev", "erkap_cost_element_category_id" => 27],
            ["code" => "9102", "name" => "Biaya Kegiatan Sosial Masyarakat", "erkap_cost_element_category_id" => 27],
            ["code" => "9108", "name" => "Biaya Sumbangan dan Hadiah", "erkap_cost_element_category_id" => 27],
            ["code" => "8021", "name" => "Biaya Pemindahan Pegawai", "erkap_cost_element_category_id" => 28],
            ["code" => "8022", "name" => "Biaya Penghargaan dan Pembinaan Pegawai", "erkap_cost_element_category_id" => 28],
            ["code" => "8111", "name" => "Biaya Penghapusan Persediaan", "erkap_cost_element_category_id" => 28],
            ["code" => "8112", "name" => "Biaya Perlengkapan Kantor dan ATK", "erkap_cost_element_category_id" => 28],
            ["code" => "8113", "name" => "Biaya Perlengkapan Pengaman dan Pakaian Pelindung", "erkap_cost_element_category_id" => 28],
            ["code" => "8114", "name" => "Biaya Perlengkapan Peralatan Mess", "erkap_cost_element_category_id" => 28],
            ["code" => "8115", "name" => "Biaya Kebutuhan Obat", "erkap_cost_element_category_id" => 28],
            ["code" => "8116", "name" => "Biaya Bahan Makanan", "erkap_cost_element_category_id" => 28],
            ["code" => "8117", "name" => "Biaya Pakaian Seragam", "erkap_cost_element_category_id" => 28],
            ["code" => "8200", "name" => "Biaya Listrik dan Air", "erkap_cost_element_category_id" => 28],
            ["code" => "8201", "name" => "Biaya Telepon, Telex dan Telegraf", "erkap_cost_element_category_id" => 28],
            ["code" => "8202", "name" => "Biaya Asuransi Aktiva Tetap", "erkap_cost_element_category_id" => 28],
            ["code" => "8203", "name" => "Biaya Asuransi Jiwa dan Purnajabatan", "erkap_cost_element_category_id" => 28],
            ["code" => "8204", "name" => "Biaya Asuransi Kesehatan", "erkap_cost_element_category_id" => 28],
            ["code" => "8600", "name" => "Biaya Penelitian dan Pengembangan", "erkap_cost_element_category_id" => 28],
            ["code" => "9010", "name" => "Biaya Jasa Penagihan", "erkap_cost_element_category_id" => 28],
            ["code" => "9100", "name" => "Biaya Jamuan/Rapat", "erkap_cost_element_category_id" => 28],
            ["code" => "9101", "name" => "Biaya Publikasi", "erkap_cost_element_category_id" => 28],
            ["code" => "9103", "name" => "Biaya Olahraga, Rekreasi, dan Seni Budaya", "erkap_cost_element_category_id" => 28],
            ["code" => "9104", "name" => "Biaya Kontribusi dan Suvenir", "erkap_cost_element_category_id" => 28],
            ["code" => "9105", "name" => "Biaya Paparan Publik", "erkap_cost_element_category_id" => 28],
            ["code" => "9106", "name" => "Biaya Iuran Keanggotan", "erkap_cost_element_category_id" => 28],
            ["code" => "9107", "name" => "Biaya Buku, Majalah, dan Surat Kabar", "erkap_cost_element_category_id" => 28],
            ["code" => "9109", "name" => "Biaya Pos Surat dan Pengiriman Barang", "erkap_cost_element_category_id" => 28],
        ];

        foreach ($costElements as $costElement) {
            $costElement['chart_of_account_id'] = $chartOfAccounts[$costElement['code']] ?? null;

            CostElement::create($costElement);
        }
    }
}
